:bug: #324 ポリシーの部分をクリックすると出る以下のエラーを修正
```
A slot prop is required. Valid slot names are "label"、"description".
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the Decorators documentation.
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring Webpack or Vite with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the Environment Variables documentation.

Error: A slot prop is required. Valid slot names are "label"、"description".
    at $64fa3d84918910a7$export$fabf2dc03a41866e (http://localhost:6008/vendors-node_modules_next_link_js-node_modules_react-aria-components_dist_Text_mjs.iframe.bundle.js:1541:83)
    at $64fa3d84918910a7$export$29f1550f4b0d4415 (http://localhost:6008/vendors-node_modules_next_link_js-node_modules_react-aria-components_dist_Text_mjs.iframe.bundle.js:1551:15)
    at $514c0188e459b4c0$var$Text (http://localhost:6008/vendors-node_modules_next_link_js-node_modules_react-aria-components_dist_Text_mjs.iframe.bundle.js:1420:80)
    at renderWithHooks (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:60608:18)
    at updateForwardRef (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:65341:20)
    at beginWork$1 (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:68008:16)
    at beginWork (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:76414:14)
    at performUnitOfWork (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:75235:12)
    at workLoopSync (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:74951:5)
    at renderRootSync (http://localhost:6008/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-54ddfe.iframe.bundle.js:74906:7)
```